name: Make release

on:
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
          token: ${{ secrets.DSFOX_GH_ACTIONS }}

      - name: Setup git
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Merge changes from `master` branch
        run: |
          git reset --hard origin/master

      - name: Create new tag and push it to repo
        id: tag
        run: |
          tag_name=v$(date +'%Y.%m.%d')

          check_tag_name:
          if [ $(git tag -l "$tag_name") ]; then
            $tag_name =~ "\A$(date +'%Y\.%m\.%d')-fix\.(\d+)\z"
            version="${BASH_REMATCH[1]:=0}"
            tag_name=v$(date +'%Y.%m.%d')-fix.$version

            goto check_tag_name
          fi
          
          git tag $tag_name
          git push origin $tag_name
          echo ::set-output name=result::$tag_name

      - name: Create release in GitHub
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.tag.outputs.result }}',
              generate_release_notes: true,
            });
